#!/bin/bash
docker run --user=$UID:nogroup --rm -ti --network="host" \
  -v $(pwd):/workspace -v $HOME/configs/:/configs \
  -e "JAVA_OPTS=-Duser.home=/configs $JAVA_OPTS" \
  amm --no-remote-logging $@
